version: '3.4'

x-common-args: &common-args
  CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
  CMAKE_VERSION: ${CMAKE_VERSION}
  PYTHON_VERSION: ${PYTHON_VERSION}
  PYTHON_VERSION_FULL: ${PYTHON_VERSION_FULL}
  CONAN_VERSION: ${CONAN_VERSION}
  LIBSTDCPP_VERSION: ${LIBSTDCPP_VERSION}
  LIBSTDCPP_PATCH_VERSION: ${LIBSTDCPP_PATCH_VERSION}
  LIBSTDCPP_MAJOR_VERSION: ${LIBSTDCPP_MAJOR_VERSION}
  DOCKER_USERNAME: ${DOCKER_USERNAME}
  DOCKER_TAG: ${DOCKER_TAG}
  DISTRO: ${DISTRO}
  DISTRO_VERSION: ${DISTRO_VERSION}

x-gcc7: &gcc7
  GCC_VERSION: ${GCC7_VERSION}

x-gcc8: &gcc8
  GCC_VERSION: ${GCC8_VERSION}

x-gcc9: &gcc9
  GCC_VERSION: ${GCC9_VERSION}

x-gcc10: &gcc10
  GCC_VERSION: ${GCC10_VERSION}

x-gcc11: &gcc11
  GCC_VERSION: ${GCC11_VERSION}

x-llvm10: &llvm10
  CLANG_VERSION: ${CLANG10_VERSION}

x-llvm11: &llvm11
  CLANG_VERSION: ${CLANG11_VERSION}

x-llvm12: &llvm12
  CLANG_VERSION: ${CLANG12_VERSION}

x-llvm13: &llvm13
  CLANG_VERSION: ${CLANG13_VERSION}


services:
  # Base image
  base:
    build:
      context: base
      dockerfile: Dockerfile
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/base-${DISTRO}:${DOCKER_TAG}
    container_name: base
    tty: true

  # Builder images
  gcc7-builder:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: gcc-builder
      args:
        <<: *common-args
        <<: *gcc7
    image: ${DOCKER_USERNAME}/gcc7-builder-${DISTRO}:${DOCKER_TAG}
    container_name: gcc7-builder
    tty: true
  gcc8-builder:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: gcc-builder
      args:
        <<: *common-args
        <<: *gcc8
    image: ${DOCKER_USERNAME}/gcc8-builder-${DISTRO}:${DOCKER_TAG}
    container_name: gcc8-builder
    tty: true
  gcc9-builder:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: gcc-builder
      args:
        <<: *common-args
        <<: *gcc9
    image: ${DOCKER_USERNAME}/gcc9-builder-${DISTRO}:${DOCKER_TAG}
    container_name: gcc9-builder
    tty: true
  gcc10-builder:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: gcc-builder
      args:
        <<: *common-args
        <<: *gcc10
    image: ${DOCKER_USERNAME}/gcc10-builder-${DISTRO}:${DOCKER_TAG}
    container_name: gcc10-builder
    tty: true
  gcc11-builder:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: gcc-builder
      args:
        <<: *common-args
        <<: *gcc11
    image: ${DOCKER_USERNAME}/gcc11-builder-${DISTRO}:${DOCKER_TAG}
    container_name: gcc11-builder
    tty: true
  clang10-builder:
    build:
      context: clang
      dockerfile: Dockerfile
      target: clang-builder
      args:
        <<: *common-args
        <<: *llvm10
    image: ${DOCKER_USERNAME}/clang10-builder-${DISTRO}:${DOCKER_TAG}
    container_name: clang10-builder
    tty: true
  clang11-builder:
    build:
      context: clang
      dockerfile: Dockerfile
      target: clang-builder
      args:
        <<: *common-args
        <<: *llvm11
    image: ${DOCKER_USERNAME}/clang11-builder-${DISTRO}:${DOCKER_TAG}
    container_name: clang11-builder
    tty: true
  clang12-builder:
    build:
      context: clang
      dockerfile: Dockerfile
      target: clang-builder
      args:
        <<: *common-args
        <<: *llvm12
    image: ${DOCKER_USERNAME}/clang12-builder-${DISTRO}:${DOCKER_TAG}
    container_name: clang12-builder
    tty: true
  clang13-builder:
    build:
      context: clang
      dockerfile: Dockerfile
      target: clang-builder
      args:
        <<: *common-args
        <<: *llvm13
    image: ${DOCKER_USERNAME}/clang13-builder-${DISTRO}:${DOCKER_TAG}
    container_name: clang13-builder
    tty: true

  # Deploy images
  gcc7-deploy:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/gcc7-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/gcc7-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: gcc7-deploy
    tty: true
  gcc8-deploy:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/gcc8-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/gcc8-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: gcc8-deploy
    tty: true
  gcc9-deploy:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/gcc9-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/gcc9-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: gcc9-deploy
    tty: true
  gcc10-deploy:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/gcc10-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/gcc10-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: gcc10-deploy
    tty: true
  gcc11-deploy:
    build:
      context: gcc
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/gcc11-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/gcc11-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: gcc11-deploy
    tty: true
  clang10-deploy:
    build:
      context: clang
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/clang10-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/clang10-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: clang10-deploy
    tty: true
  clang11-deploy:
    build:
      context: clang
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/clang11-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/clang11-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: clang11-deploy
    tty: true
  clang12-deploy:
    build:
      context: clang
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/clang12-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/clang12-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: clang12-deploy
    tty: true
  clang13-deploy:
    build:
      context: clang
      dockerfile: Dockerfile
      target: deploy
      cache_from:
        - ${DOCKER_USERNAME}/clang13-builder-${DISTRO}:${DOCKER_TAG}
      args:
        <<: *common-args
    image: ${DOCKER_USERNAME}/clang13-deploy-${DISTRO}:${DOCKER_TAG}
    container_name: clang13-deploy
    tty: true

  # Images
  gcc7:
    build:
      context: gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *gcc7
    image: ${DOCKER_USERNAME}/gcc7-${DISTRO}:${DOCKER_TAG}
    container_name: gcc7
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  gcc8:
    build:
      context: gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *gcc8
    image: ${DOCKER_USERNAME}/gcc8-${DISTRO}:${DOCKER_TAG}
    container_name: gcc8
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  gcc9:
    build:
      context: gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *gcc9
    image: ${DOCKER_USERNAME}/gcc9-${DISTRO}:${DOCKER_TAG}
    container_name: gcc9
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  gcc10:
    build:
      context: gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *gcc10
    image: ${DOCKER_USERNAME}/gcc10-${DISTRO}:${DOCKER_TAG}
    container_name: gcc10
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  gcc11:
    build:
      context: gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *gcc11
    image: ${DOCKER_USERNAME}/gcc11-${DISTRO}:${DOCKER_TAG}
    container_name: gcc11
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  clang10:
    build:
      context: clang
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *llvm10
    image: ${DOCKER_USERNAME}/clang10-${DISTRO}:${DOCKER_TAG}
    container_name: clang10
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  clang11:
    build:
      context: clang
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *llvm11
    image: ${DOCKER_USERNAME}/clang11-${DISTRO}:${DOCKER_TAG}
    container_name: clang11
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  clang12:
    build:
      context: clang
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *llvm12
    image: ${DOCKER_USERNAME}/clang12-${DISTRO}:${DOCKER_TAG}
    container_name: clang12
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data
  clang13:
    build:
      context: clang
      dockerfile: Dockerfile
      args:
        <<: *common-args
        <<: *llvm13
    image: ${DOCKER_USERNAME}/clang13-${DISTRO}:${DOCKER_TAG}
    container_name: clang13
    tty: true
    ports:
      - 2222:22
    volumes:
      - conan_data:/home/conan/.conan/data

volumes:
  conan_data: